///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "F9B868A1-9C51-442E-B6B7-FADFEFADF77F"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (MyInterpreter)"
#define COCLASS_UUID "14603904-D821-4F1B-A7B7-8969EDEEAD17"
#define COCLASS_NAME "MGA Interpreter CoClass (MyInterpreter)"
#define COCLASS_PROGID "MGA.Interpreter.MyInterpreter"

#define COCLASS_UUID_EXPLODED1  0x14603904
#define COCLASS_UUID_EXPLODED2   0xd821
#define COCLASS_UUID_EXPLODED3   0x4f1b
#define COCLASS_UUID_EXPLODED4   0xa7
#define COCLASS_UUID_EXPLODED5   0xb7
#define COCLASS_UUID_EXPLODED6   0x89
#define COCLASS_UUID_EXPLODED7   0x69
#define COCLASS_UUID_EXPLODED8   0xed
#define COCLASS_UUID_EXPLODED9   0xee
#define COCLASS_UUID_EXPLODED10  0xad
#define COCLASS_UUID_EXPLODED11  0x17


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME _T("MyInterpreter")


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT _T("MyInterpreter Interpreter")

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS _T("Logicus")


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
