///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "226499F6-8430-40C3-A29D-ACA1D113AA2C"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (BON2Component1)"
#define COCLASS_UUID "04840FBC-07A5-4B92-A0C4-2EECD797E9EE"
#define COCLASS_NAME "MGA Interpreter CoClass (BON2Component1)"
#define COCLASS_PROGID "MGA.Interpreter.BON2Component1"

#define COCLASS_UUID_EXPLODED1  0x4840fbc
#define COCLASS_UUID_EXPLODED2   0x7a5
#define COCLASS_UUID_EXPLODED3   0x4b92
#define COCLASS_UUID_EXPLODED4   0xa0
#define COCLASS_UUID_EXPLODED5   0xc4
#define COCLASS_UUID_EXPLODED6   0x2e
#define COCLASS_UUID_EXPLODED7   0xec
#define COCLASS_UUID_EXPLODED8   0xd7
#define COCLASS_UUID_EXPLODED9   0x97
#define COCLASS_UUID_EXPLODED10  0xe9
#define COCLASS_UUID_EXPLODED11  0xee


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME _T("BON2Component1")


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT _T("BON2Component1 Interpreter")

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS _T("CyberSecurity")


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
